FROM node:22-alpine AS builder
WORKDIR /app

# Declare build-time env vars so Vite can bake them into the bundle
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_SUPABASE_PROJECT_ID
ARG VITE_WP_SSO_SECRET
ARG VITE_PORTAL_EMAIL
ARG VITE_PORTAL_PASSWORD

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_SUPABASE_PROJECT_ID=$VITE_SUPABASE_PROJECT_ID
ENV VITE_WP_SSO_SECRET=$VITE_WP_SSO_SECRET
ENV VITE_PORTAL_EMAIL=$VITE_PORTAL_EMAIL
ENV VITE_PORTAL_PASSWORD=$VITE_PORTAL_PASSWORD

COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist

EXPOSE 3000
CMD ["serve", "-s", "dist"]
